<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageType>Template</PackageType>
    <Version>1.0</Version>
    <PackageId>Transpose.Template</PackageId>
    <Title>Transpose Template</Title>
    <Authors>Curiosity GmbH</Authors>
    <Company>Curiosity GmbH</Company>
    <Description>Templates to use when creating a Transpose based application.</Description>
    <Copyright>Copyright (c) 2019-2022, Curiosity GmbH. All rights reserved.</Copyright>
    <PackageTags>dotnet-new;templates;c#;javascript;transpose;tps</PackageTags>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IncludeContentInPack>true</IncludeContentInPack>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <ContentTargetFolders>content</ContentTargetFolders>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/curiosity-ai/transpose</PackageProjectUrl>
    <PackageIcon>transpose.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="templates\**\*" Exclude="templates\**\bin\**;templates\**\obj\**" />
    <Compile Remove="**\*" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\logo\transpose.png" Link="transpose.png" Pack="true" PackagePath="\" />
    <None Include="..\..\README.md" Link="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>