<Project Sdk="Transpose.Build.Target/26.7.2669">
    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <LangVersion>7.2</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Transpose" Version="25.11.62743" />
        <PackageReference Include="Transpose.Core" Version="25.11.62746" />
        <PackageReference Include="Transpose.Newtonsoft.Json" Version="25.11.62749" />
        <PackageReference Include="Tesserae" Version="2026.1.63737" />
    </ItemGroup>
</Project>
